version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/development/nginx/nginx.docker
        volumes:
            -  ./:/var/www
            - ./docker/development/nginx/log:/var/log/nginx
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        links:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: ./
            dockerfile: docker/development/php-fpm/php-fpm8-1.docker
        container_name: php-fpm
        restart: unless-stopped
        tty: true
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=127.0.0.1"
        volumes:
            -  ./:/var/www
        networks:
            - app-network

    php-cli:
        build:
            context: ./
            dockerfile: docker/development/php-cli/php-cli8-1.docker
        container_name: php-cli
        restart: unless-stopped
        tty: true
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=127.0.0.1"
        volumes:
            -  ./:/var/www
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    node:
        build:
            context: ./
            dockerfile: docker/development/node/node.docker
        container_name: node
        volumes:
            - ./:/var/www
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge